<a href="https://colab.research.google.com/github/piyushpp07/DataScience/blob/main/numpy_excercise0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import numpy as np**

In [5]:
import numpy as np

**Create an array of 10 zeros**

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Create an array of 10 ones**

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Create an array of 10 fives**

In [9]:
np.array([5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0])

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
np.array([5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0])

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Create an array of the integers from 10 to 50**

In [11]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Create an array of all the even integers from 10 to 50**

In [12]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Create a 3x4 matrix with numbers ranging from 0 to 12**

In [13]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**Create a 3x3 identity matrix**

In [14]:
np.array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Use Numpy to generate a random number between 0 and 1**

In [15]:
np.random.rand(0,1)

array([], shape=(0, 1), dtype=float64)

**Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution**

In [16]:
np.random.normal(0,1,25)

array([-0.65766164, -2.51458008,  0.05596496,  0.4391796 ,  0.58056164,
        0.73243707,  0.60529322,  0.95482014, -0.42539149, -2.19753422,
        1.29700728, -1.01529293, -0.75239691,  0.59362275, -0.03728624,
        2.61318417, -0.81657687, -0.55318946,  0.04029252,  0.76114909,
        0.22628213, -0.97813916,  0.11541482, -0.3403053 , -1.02946584])

**Create an (10x10)array having numbers from 0.01 to 1 increasing by 0.01**

In [23]:
q=np.arange(0.01,1.01,0.01).reshape(100)
p=q.reshape(10,10)
p

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**Create a (10x10)array of 100 linearly spaces numbers from 0.01 to 1**

In [24]:
q=np.arange(0.01,1.01,0.01).reshape(100)
p=q.reshape(10,10)
p

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#Numpy Indexing and Selection

In [26]:
a=np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

a[2:5,3:0:-1]

array([[14, 13, 12],
       [19, 18, 17],
       [24, 23, 22]])

**extract array**

[
  [12,13,14],

  [17,18,19],

  [22,23,24]
]

In [27]:
a[2:5,3:1]

array([], shape=(3, 0), dtype=int64)

**extract array**

[
  [14, 13, 12],

  [19, 18, 17],

  [24, 23, 22]
]

In [28]:
a[5:1:-1,3:0:-1]

array([[24, 23, 22],
       [19, 18, 17],
       [14, 13, 12]])

**extract array**

[
  [24, 23, 22],

  [19, 18, 17],

  [14, 13, 12],  
]

In [29]:
a[5:1:-1,3:0:-1]

array([[24, 23, 22],
       [19, 18, 17],
       [14, 13, 12]])

#Split Concatinate

In [31]:
ar = np.arange(2,10)
ar

array([2, 3, 4, 5, 6, 7, 8, 9])

**Split array to generate 3 arrays with content**

[2,3,4]

[5, 6]

[]

[7,8,9]

In [40]:
a=ar[0:3]
b=ar[3:5]
c=ar[5:5]
d=ar[5:9]
print(a)
print(b)
print(c)
print(d)

[2 3 4]
[5 6]
[]
[7 8 9]


In [53]:
m=np.arange(1,10)
m.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Concatinate array to create new array with content**

[
  [1,2,3],

  [4,5,6],
  
  [7,8,9]
]

In [54]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9, 10],
              [11, 12, 13, 14]
])

**Concatinate array to create new array with content**

[

  [1,2,3, 7,8,9, 10],

  [4,5,6, 11, 12, 13, 14]
  
]

In [55]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  7,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13, 14]])

#Broadcasting and Indexing

In [75]:
np.random.rand(12,4)

array([[0.52979748, 0.53662162, 0.39902793, 0.92458692],
       [0.61105843, 0.94739725, 0.24908317, 0.0950929 ],
       [0.6249101 , 0.90875924, 0.62304232, 0.18475695],
       [0.14660645, 0.83424013, 0.39425135, 0.22788239],
       [0.90087093, 0.1399322 , 0.50569939, 0.60142151],
       [0.87631544, 0.24156887, 0.06432209, 0.45248651],
       [0.83952439, 0.60608627, 0.56010461, 0.64708435],
       [0.076231  , 0.30095558, 0.21189983, 0.99883443],
       [0.06378322, 0.05810068, 0.97434915, 0.72528653],
       [0.58165507, 0.88338958, 0.12322288, 0.53768232],
       [0.492547  , 0.40493578, 0.64847768, 0.93350651],
       [0.38214401, 0.62338989, 0.71885821, 0.54002423]])

**create new array containing all numbers which are smaller than 10 in ar**

In [56]:
ar=np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**create new array containing all numbers which are in range [3, 11] in ar**

In [57]:
ar[2:10]

array([4, 5, 6, 7, 8, 9])

**count how many numbers are minimum in ar**

example for arr = [2, 4, 6, 2, 9, 2]

min is 2

there are 3 occurences of 2

In [61]:
a=np.min(ar)
z=np.count_nonzero(ar==a)
print(z)

1


**Create an array of length 20 with first 15 numbers equal to 2 and last 5 numbers = -5**

In [64]:
p=np.array([2]*15)
q=np.array([-5]*5)
z=np.concatenate((p,q),axis=0)
print(z)

[ 2  2  2  2  2  2  2  2  2  2  2  2  2  2  2 -5 -5 -5 -5 -5]


In [67]:
mat = np.round(np.random.rand(50)*100).reshape(5,10)
mat

array([[57., 45., 84., 82., 96., 93., 79., 74., 94., 27.],
       [82., 53., 34., 16.,  8., 41., 86., 72., 85., 24.],
       [60., 34., 78., 33., 26., 95., 94., 11.,  4., 53.],
       [79., 39., 94., 75., 17., 96., 56., 70., 37., 93.],
       [65., 12.,  3., 20., 34., 25., 88., 65., 54., 25.]])

**Sum min max of all elements of matrix**

In [70]:
np.min(mat)+np.max(mat)

99.0

**Standard deviation of mat**

In [71]:
np.std(mat)

29.46496903103752

**Sum of all columns of mat**

In [73]:
col_sum=np.sum(mat,axis=0)
print(col_sum)

[343. 183. 293. 226. 181. 350. 403. 292. 274. 222.]
