<a href="https://colab.research.google.com/github/piyushpp07/DataScience/blob/main/python_basics_datascience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")
string = "piyush paradkar"
print(string)
a,b,c= 10,20,30
print(a,b,c)

Hello World
piyush paradkar
10 20 30


In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
p1="Piyush"
for i in p1:
  print(i)
if "iy" in p1:
  print("Yes")
else :
  print("No")

P
i
y
u
s
h
Yes


In [ ]:
p2="Hello my name is piyush"
print(p2.split(" "))

['Hello', 'my', 'name', 'is', 'piyush']


In [17]:
import numpy as np


In [12]:
qq=np.array([1,2,3,4,5],dtype='int8')
%timeit qq.sum()

The slowest run took 1744.89 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.32 µs per loop


In [11]:
p= [1]*100
%timeit sum(p)

1000000 loops, best of 5: 871 ns per loop


In [18]:
np.ones(10,dtype='int32')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [19]:
np.ones((2,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [22]:
ar=np.arange(3,20,3)
ar

array([ 3,  6,  9, 12, 15, 18])

In [23]:
ar[2:4]

array([ 9, 12])

In [27]:
ar2=ar[2:5]
print(ar)
print(ar2)
ar2[0]=1000
print(ar)
print(ar2)

[1000    6    9   12   15   18]
[ 9 12 15]
[1000    6 1000   12   15   18]
[1000   12   15]
